-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 14:40:19 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reviewDB
-- -----------------------------------------------------
-- 评审系统数据库
DROP SCHEMA IF EXISTS `reviewDB` ;

-- -----------------------------------------------------
-- Schema reviewDB
--
-- 评审系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reviewDB` DEFAULT CHARACTER SET utf8 ;
USE `reviewDB` ;

-- -----------------------------------------------------
-- Table `reviewDB`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`department` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`department` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `type` INT UNSIGNED NULL COMMENT '1，2）机关and学院',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '机关部门';


-- -----------------------------------------------------
-- Table `reviewDB`.`title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`title` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`title` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '职称';


-- -----------------------------------------------------
-- Table `reviewDB`.`eduction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`eduction` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`eduction` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '学历';


-- -----------------------------------------------------
-- Table `reviewDB`.`degree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`degree` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`degree` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '学位';


-- -----------------------------------------------------
-- Table `reviewDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`user` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`user` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `number` VARCHAR(45) NULL COMMENT '教工号',
  `sex` VARCHAR(10) NULL COMMENT '性别',
  `name` VARCHAR(45) NULL COMMENT '姓名',
  `pic` VARCHAR(450) NULL COMMENT '头像',
  `type` INT NULL COMMENT '类型\n1-user\n2-admin\n3-root\n4-projectperson',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `email` VARCHAR(45) NULL COMMENT '邮箱地址',
  `birthday` VARCHAR(45) NULL COMMENT '用户',
  `backup_one` VARCHAR(45) NULL COMMENT '备用',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `department_id` CHAR(32) NOT NULL COMMENT '',
  `title_id` CHAR(32) NOT NULL COMMENT '',
  `eduction_id` CHAR(32) NOT NULL COMMENT '',
  `degree_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_user_department1_idx` (`department_id` ASC)  COMMENT '',
  INDEX `fk_user_title1_idx` (`title_id` ASC)  COMMENT '',
  INDEX `fk_user_eduction1_idx` (`eduction_id` ASC)  COMMENT '',
  INDEX `fk_user_degree1_idx` (`degree_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `reviewDB`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_title1`
    FOREIGN KEY (`title_id`)
    REFERENCES `reviewDB`.`title` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_eduction1`
    FOREIGN KEY (`eduction_id`)
    REFERENCES `reviewDB`.`eduction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_degree1`
    FOREIGN KEY (`degree_id`)
    REFERENCES `reviewDB`.`degree` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户';


-- -----------------------------------------------------
-- Table `reviewDB`.`expert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`expert` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`expert` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `post` VARCHAR(45) NULL COMMENT '职务',
  `school` VARCHAR(45) NULL COMMENT '学校',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` CHAR(32) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `title_id` CHAR(32) NOT NULL COMMENT '',
  `degree_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_expert_title1_idx` (`title_id` ASC)  COMMENT '',
  INDEX `fk_expert_degree1_idx` (`degree_id` ASC)  COMMENT '',
  CONSTRAINT `fk_expert_title1`
    FOREIGN KEY (`title_id`)
    REFERENCES `reviewDB`.`title` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expert_degree1`
    FOREIGN KEY (`degree_id`)
    REFERENCES `reviewDB`.`degree` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '专家';


-- -----------------------------------------------------
-- Table `reviewDB`.`class_one`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`class_one` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`class_one` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `is_deleted` TINYINT(1) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '项目大类',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '项目大类';


-- -----------------------------------------------------
-- Table `reviewDB`.`class_two`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`class_two` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`class_two` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `is_deleted` TINYINT(1) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `class_one_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_classTwo_classOne_idx` (`class_one_id` ASC)  COMMENT '',
  CONSTRAINT `fk_classTwo_classOne`
    FOREIGN KEY (`class_one_id`)
    REFERENCES `reviewDB`.`class_one` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '项目子类';


-- -----------------------------------------------------
-- Table `reviewDB`.`rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`rules` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`rules` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `details` VARCHAR(45) NULL COMMENT '细则详情',
  `score` VARCHAR(45) NULL COMMENT '细则分值',
  `is_deleted` TINYINT(1) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '评审细则';


-- -----------------------------------------------------
-- Table `reviewDB`.`review_program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`review_program` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`review_program` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `class_name` VARCHAR(45) NULL COMMENT '类名（方法名）',
  `url` VARCHAR(450) NULL COMMENT '界面地址',
  `creation_time` DATETIME NULL COMMENT '',
  `careator` VARCHAR(45) NULL COMMENT '',
  `score` VARCHAR(45) NULL COMMENT '',
  `is_deleted` TINYINT(1) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `rules_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_review_program_rules1_idx` (`rules_id` ASC)  COMMENT '',
  CONSTRAINT `fk_review_program_rules1`
    FOREIGN KEY (`rules_id`)
    REFERENCES `reviewDB`.`rules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '评审方案';


-- -----------------------------------------------------
-- Table `reviewDB`.`class_three`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`class_three` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`class_three` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `start_time` DATETIME NULL COMMENT '开始时间',
  `end_time` DATETIME NULL COMMENT '结束时间',
  `is_deleted` TINYINT(1) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `class_two_id` CHAR(32) NOT NULL COMMENT '',
  `reviewprogram_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_classThree_classTwo1_idx` (`class_two_id` ASC)  COMMENT '',
  INDEX `fk_classThree_reviewprogram1_idx` (`reviewprogram_id` ASC)  COMMENT '',
  CONSTRAINT `fk_classThree_classTwo1`
    FOREIGN KEY (`class_two_id`)
    REFERENCES `reviewDB`.`class_two` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classThree_reviewprogram1`
    FOREIGN KEY (`reviewprogram_id`)
    REFERENCES `reviewDB`.`review_program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '项目表';


-- -----------------------------------------------------
-- Table `reviewDB`.`subjectcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`subjectcategory` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`subjectcategory` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '课题类别';


-- -----------------------------------------------------
-- Table `reviewDB`.`disciplinecategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`disciplinecategory` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`disciplinecategory` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `is_deleted` TINYINT(1) NULL COMMENT '',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '学科门类';


-- -----------------------------------------------------
-- Table `reviewDB`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`project` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`project` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `file` VARCHAR(450) NULL COMMENT '文件',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `backup_four` VARCHAR(45) NULL COMMENT '',
  `backup_five` VARCHAR(45) NULL COMMENT '',
  `class_three_id` CHAR(32) NOT NULL COMMENT '',
  `user_id` CHAR(32) NOT NULL COMMENT '',
  `subjectcategory_id` CHAR(32) NOT NULL COMMENT '',
  `disciplinecategory_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_project_classThree1_idx` (`class_three_id` ASC)  COMMENT '',
  INDEX `fk_project_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_project_subjectcategory1_idx` (`subjectcategory_id` ASC)  COMMENT '',
  INDEX `fk_project_disciplinecategory1_idx` (`disciplinecategory_id` ASC)  COMMENT '',
  CONSTRAINT `fk_project_classThree1`
    FOREIGN KEY (`class_three_id`)
    REFERENCES `reviewDB`.`class_three` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reviewDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_subjectcategory1`
    FOREIGN KEY (`subjectcategory_id`)
    REFERENCES `reviewDB`.`subjectcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_disciplinecategory1`
    FOREIGN KEY (`disciplinecategory_id`)
    REFERENCES `reviewDB`.`disciplinecategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '项目流水表';


-- -----------------------------------------------------
-- Table `reviewDB`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`comment` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`comment` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `content` VARCHAR(45) NULL COMMENT '',
  `class` VARCHAR(45) NULL COMMENT '',
  `score` VARCHAR(45) NULL COMMENT '分数',
  `sort` INT NULL COMMENT '排序',
  `is_pass` VARCHAR(45) NULL COMMENT '通过与否',
  `comment_time` VARCHAR(45) NULL COMMENT '评审时间',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `backup_four` VARCHAR(45) NULL COMMENT '',
  `backup_five` VARCHAR(45) NULL COMMENT '',
  `project_id` CHAR(32) NOT NULL COMMENT '',
  `expert_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_comment_project1_idx` (`project_id` ASC)  COMMENT '',
  INDEX `fk_comment_expert1_idx` (`expert_id` ASC)  COMMENT '',
  CONSTRAINT `fk_comment_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `reviewDB`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_expert1`
    FOREIGN KEY (`expert_id`)
    REFERENCES `reviewDB`.`expert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '评审结果';


-- -----------------------------------------------------
-- Table `reviewDB`.`AssessmentResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`AssessmentResults` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`AssessmentResults` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `score` VARCHAR(45) NULL COMMENT '得分',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  `comment_id` CHAR(32) NOT NULL COMMENT '',
  `rules_id` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_AssessmentResults_comment1_idx` (`comment_id` ASC)  COMMENT '',
  INDEX `fk_AssessmentResults_rules1_idx` (`rules_id` ASC)  COMMENT '',
  CONSTRAINT `fk_AssessmentResults_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `reviewDB`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AssessmentResults_rules1`
    FOREIGN KEY (`rules_id`)
    REFERENCES `reviewDB`.`rules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '评分细则结果表';


-- -----------------------------------------------------
-- Table `reviewDB`.`announcement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviewDB`.`announcement` ;

CREATE TABLE IF NOT EXISTS `reviewDB`.`announcement` (
  `id` CHAR(32) NOT NULL COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `content` VARCHAR(1000) NULL COMMENT '内容',
  `creation_time` DATETIME NULL COMMENT '',
  `creator` VARCHAR(45) NULL COMMENT '',
  `backup_one` VARCHAR(45) NULL COMMENT '',
  `backup_two` VARCHAR(45) NULL COMMENT '',
  `backup_three` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '公告';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
